client_config_backend: settings
client_config:
  client_id: 398922604890-0fja9q53men7rsg9eo20ujm6jc8ao3u5.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
